Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -117,8 +117,8 @@ stages:
         echo "Number of high vulnerabilities: $high_count"
         
         if [ "$critical_count" -gt 20 ]; then
-        echo "Error: Number of critical vulnerabilities ($critical_count) exceeds the threshold."
-        exit 1
+          echo "Error: Number of critical vulnerabilities ($critical_count) exceeds the threshold."
+          exit 1
         fi
       displayName: 'Count Critical Vulnerabilities'
 
@@ -144,7 +144,7 @@ stages:
     - script: |
         fatal_count=$(jq '[.details[] | select(.level == "FATAL")] | length' dockle-results-$(Build.BuildId).json)
         if [ "$fatal_count" -gt 0 ]; then
-        echo "Error: There are $fatal_count FATAL issues."
-        exit 1
+          echo "Error: There are $fatal_count FATAL issues."
+          exit 1
         fi
       displayName: 'Fail on FATAL Issues'
