Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -187,16 +187,25 @@ stages:
         docker pull zaproxy/zap-stable:latest
 
         echo "Running OWASP ZAP DAST scan on $(url_to_scan)..."
-        docker run --rm -u zap \
+        docker run --rm \
           -v $(Build.SourcesDirectory)/zap_reports:/zap/wrk:rw \
-          zaproxy/zap-stable:latest zap-baseline.py -t $(url_to_scan) -r /zap/wrk/zap_report.html -J /zap/wrk/zap_output.json
+          zaproxy/zap-stable:latest zap-baseline.py -t $(url_to_scan) -r /zap/wrk/zap_report.html
 
-        echo "Scan completed. Check the zap_reports directory for the JSON report."
+        echo "Scan completed. Check the zap_reports directory for the HTML report."
       displayName: 'Run OWASP ZAP DAST Scan'
     - script: |
-        echo "Displaying JSON Output..."
-        cat $(Build.SourcesDirectory)/zap_reports/zap_output.json
-      displayName: 'Print JSON Output'
+        echo "Analyzing ZAP Scan HTML report for High risk vulnerabilities..."
+        high_count=$(grep -o 'High</div></td><td align="center"><div>[^0]' $(Build.SourcesDirectory)/zap_reports/zap_report.html | wc -l)
+        
+        echo "Number of High vulnerabilities: $high_count"
+        if [ "$high_count" -gt 0 ]; then
+          echo "Error: High vulnerabilities detected. Number of High vulnerabilities: $high_count"
+          exit 1
+        else
+          echo "No High vulnerabilities detected. Proceeding..."
+        fi
+      displayName: 'Analyze ZAP Scan Results'
+
 
     # - script: |
     #     echo "Printing ZAP Scan JSON output for review..."
